name: Infra Deployment and Training

on:
  push:
    paths: 
      - '.github/workflows/train_model.yml' 
      - 'code/**' 
  repository_dispatch:
   types: [storage-blobcreated, storage-blobdeleted]

jobs:
  deployment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
      
      # Connect the Azure Machine Learning Workspace
    - name: Connect Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
